[package]
name = "feather-chunk"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-blocks = { path = "../blocks" }
feather-biomes = { path = "../biomes" }
feather-util = { path = "../util" }

bitflags = "1.2"
ahash = "0.3"
smallvec = "1.3"
